cms_user:
    path:     /
    defaults: { _controller: "CustomCMSBundle:User:index" }

cms_user_show:
    path:     /{id}/show
    defaults: { _controller: "CustomCMSBundle:User:show" }

cms_user_new:
    path:     /new
    defaults: { _controller: "CustomCMSBundle:User:new" }

cms_user_create:
    path:     /create
    defaults: { _controller: "CustomCMSBundle:User:create" }
    requirements: { _method: post }

cms_user_edit:
    path:     /{id}/edit
    defaults: { _controller: "CustomCMSBundle:User:edit" }

cms_user_update:
    path:     /{id}/update
    defaults: { _controller: "CustomCMSBundle:User:update" }
    requirements: { _method: post|put }

cms_user_delete:
    path:     /{id}/delete
    defaults: { _controller: "CustomCMSBundle:User:delete" }
    requirements: { _method: post|delete }
